In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__

'2.12.0'

DATA PROCESSING


In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Label encoding : converting the values(strings) in data into binary values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

BUILDING ANN

initializing ANN

In [ ]:
ann = tf.keras.models.Sequential()

adding input and first hidden layer
input layer activation function should be relu

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))


second hidden layer addition

In [ ]:
ann.add(tf.keras.layers.Dense(units=8, activation ='relu'))


output layer addition
output layer activation function should be sigmoid for binary output and more probabilities

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation ='sigmoid'))


TRAINING ANN

compiling ANN



In [ ]:
ann.compile(optimizer = 'adam' ,loss = 'binary_crossentropy' , metrics = ['accuracy'])

for binary classification the loss function is binary_crossentropy and for non binary the loss function is categorical_crossentropy function


Training the ANN

In [ ]:
ann.fit(X_train ,y_train, batch_size = 32, epochs = 150)

Epoch 1/150
250/250 [==============================] - 1s 2ms/step - loss: 0.6127 - accuracy: 0.7122
Epoch 2/150
250/250 [==============================] - 0s 2ms/step - loss: 0.4782 - accuracy: 0.7985
Epoch 3/150
250/250 [==============================] - 0s 2ms/step - loss: 0.4405 - accuracy: 0.8106
Epoch 4/150
250/250 [==============================] - 0s 2ms/step - loss: 0.4230 - accuracy: 0.8190
Epoch 5/150
250/250 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 0.8226
Epoch 6/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3932 - accuracy: 0.8276
Epoch 7/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3819 - accuracy: 0.8296
Epoch 8/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3740 - accuracy: 0.8306
Epoch 9/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3688 - accuracy: 0.8321
Epoch 10/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3647 - accura

EVALUATION OF THE MODEL


In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000,]])) >0.5)

1/1 [==============================] - 0s 19ms/step
[[False]]


PREDICTIONS

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


CONFUSION MATRIX

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1543   42]
 [ 292  123]]


0.833